#!/bin/bash

#set -e

echo "Install Imgproxy for Centos7";

sudo yum install redhat-lsb-core -y;

cd $HOME;
# Install and enable the EPEL RPM package on Amazon Linux 2
#yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y;

# Install the Remi repository configuration package
#yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y;

# Install the yum-utils package (for the yum-config-manager command)
#yum install yum-utils -y;

echo "*********************** yum config manager";

# Command to enable the repository
yum-config-manager --enable remi;

yum install build-essential pkg-config libglib2.0-dev libexpat1-dev -y;

yum install glib2-devel -y;
sudo ldconfig;


sudo cat >> /etc/bashrc <<EOF
export CGO_LDFLAGS_ALLOW="-s|-w"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
export PATH=/opt/imgproxy/bin/:$PATH
EOF

# fix rev0
# export CGO_LDFLAGS_ALLOW=".*"
export CGO_LDFLAGS_ALLOW="-s|-w"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig/:$PKG_CONFIG_PATH
export PATH=/opt/imgproxy/bin/:$PATH

echo "Install Golang v1.11 via GVM";

# fix
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer);
source /root/.gvm/scripts/gvm;
gvm install go1.4;
gvm use go1.4 [--default];
# fix (1.11 old)
gvm install go1.13;
gvm use go1.13 [--default];

go version;

# fix
echo "/usr/local/lib" >> /etc/ld.so.conf.d/usrlocal.conf
ldconfig -v

sudo mkdir -p /opt/imgproxy/bin
sudo mkdir -p /opt/imgproxy/etc

mkdir gopath
cd gopath
export GOPATH=`pwd`
echo "New gopath: $GOPATH"
echo "Start building..."
go get -f -u github.com/DarthSim/imgproxy
echo "Building complete"
cp $GOPATH/bin/imgproxy /opt/imgproxy/bin/imgproxy
echo "Binary imgproxy copy to /opt/imgproxy/bin/imgproxy: "
ls -lah /opt/imgproxy/bin/imgproxy


